# Generated by Django 5.0.4 on 2024-04-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=3)),
                ('carshow', models.CharField(choices=[('Chi', 'Chicago Auto Show'), ('NAi', 'North American International Auto Show'), ('SFi', 'SanFrancisco International Auto Show'), ('NYi', 'New York International Auto Show'), ('GNR', 'Grand National Roadster Show')], default='Chi', max_length=30)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
