# Generated by Django 5.0.4 on 2024-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_carshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshow',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
